os: linux

language: elixir
elixir:
  - 1.9
  - 1.8
  - 1.7
  - 1.6
  - 1.5

cache:
  directories:
    - deps
    - ~/.mix
    - _build

install:
  - mix local.hex --force
  - mix do deps.get, deps.compile, compile --warnings-as-errors

script:
  - PROPCHECK_DEBUG=1 PROPCHECK_VERBOSE=1 PROPCHECK_NUMTESTS=200 PROPCHECK_SEARCH_STEPS=1000 mix tests --cover --trace
  - mix credo --strict
  - env MIX_ENV=test mix dialyzer
